### ISSUE TITLE
add topics materials-science, crystal-plasticity

### ISSUE THREAD

**Issue by Beliavsky** [ngrilli/c_pfor_am#1]
I suggest adding the topics `materials-science`, `crystal-plasticity` in the About section.

Thanks for your project. I have added your repo to the Materials Science section of a [list of Fortran codes](https://github.com/Beliavsky/Fortran-code-on-GitHub) that I maintain.

**Comment by ngrilli** [comment]
@Beliavsky  thank you for your comment.
I have added the topics as you suggested.
Best Regards,
Nicolò
