### ISSUE TITLE
gfortran version

### ISSUE THREAD

**Issue by Gaolejiang** [ngrilli/c_pfor_am#4]
Hi ngrilli,
Thank you for sharing the code！An error occurred when I ‘make',The system prompts that the version of my GNU Fortran is different from that of the compiled. mod file. My gfortran is 7.5.0.What version  of gfortran do you use?

![image](https://user-images.githubusercontent.com/75123243/196412346-8abd9861-4433-4fbf-97f5-df02a5a052fa.png)

**Comment by ngrilli** [comment]
@Gaolejiang  this is not due to the fortran version.
As written in the in installation instructions, you have first to:

make Bristol_CP

then

make

Alternatively, if you don't plan to use the fortran code,
you can cancel /test/plugins/ folder

Best Regards,
Nicolò
